clear all
%close all
clc
%%
colorMap = load('Ha2ColorMap.mat').Ha2ColorMap;
%%
% This is the main code of VKPlate. It calls a parameter file generated
% by genparams.m, and use an energy exact scheme to
% compute all the modal displacement of a nonlinear plate. It also has a
% comparison with Stormer-Verlet integration scheme.
%
% The input file should include :
% 
%   USEFUL FOR CONTROL
%       BCsPhi - Displacement boundary conditions   | 4 x 2 vector
%       BCsPsi - Stress boundary conditions         | 4 x 2 vector
%       Om2 - Angular frequency of the Psi modes    | Nmodes x 1 vector
%       Lx - x length of the plate                  | float
%       Ly - y length of the plate                  | float
%       X - x space                                 | Ny+1 x Nx+1 matrix
%       Y - y space                                 | Ny+1 x Nx+1 matrix
%
%   USED FOR COMPUTATION
%       E - Young modulus                           | float
%       rho - Density                               | float
%       nu - Poisson's rastio                        | float
%       h - Space step                              | float
%       Lz - Thickness of the plate                 | float
%       Nmodes  - Number of modes                   | float
%       Hv - Coupling coeficients                   | Nmodes x Nmodes x Nmodes matrix
%       Nx - Number of points in the x direction    | float
%       Ny - Number of points in the y direction    | float
%       Om - Angular frequency of the Phi modes     | Nmodes x 1 vector
%       Phi - Eigenvectors of displacement          | (Nx+1*Ny+1) x Nmodes matrix
%       Psi - Eigenvectors of stress                | (Nx+1*Ny+1) x Nmodes matrix
%       zetafourth - Eigenvalues of the stress      | Nmodes x 1 vector
%
% The raw output is the Q matrix, that can be transformed by to physical
% displacement (w) by projecting it on the Phi vector.


%% Loading parameter file

% load("./param/Test5mode.mat"); %Parameter file is generated by main
% Npsi=Nmodes;
% load("./param/Test5modev2.mat") % This one is for a rectangular plate but works amazing
% Npsi=Nmodes;
%load("./param/dump.mat")
%load("./param/Square40mum30Phi150Psi.mat")
%load("./param/Test1mode.mat")
%load("./param/Test6modesgreen.mat")
%load("./param/Test6modesmetal.mat")

%load("./param/Test50modesgreen100PsiT=3.6.mat")
load("./param/Test50modespurple100PsiT=1.mat")
%% Useful coupling matrices

Hmod=1;

Hv=Hv*Hmod;

for p = 1:Nmodes
    for q = p:Nmodes
        for i = 1:Npsi
            Hv4(i,p,q)= Hv(i,p,q)/zetafourth(i);
            Hv4(i,q,p)= Hv(i,q,p)/zetafourth(i);
        end
    end
end


for p = 1:Nmodes
    for q = p:Nmodes
        for i = 1:Npsi
            Hv2(i,p,q)= Hv(i,p,q)/sqrt(zetafourth(i));
            Hv2(i,q,p)= Hv(i,q,p)/sqrt(zetafourth(i));
        end
    end
end
Hv0= reshape(Hv,[Npsi*Nmodes,Nmodes]);
Hv2 = reshape(Hv2,[Npsi*Nmodes,Nmodes]); % reshape of the tensor into a matrix
Hv4 = reshape(Hv4,[Npsi*Nmodes,Nmodes]); % reshape of the tensor into a matrix

%% Switch cases
shouldtestSV = true ; % Make the comparison with Stormer Verlet if true
shouldtestSAV = false ;
shouldplotSAV = false ; % Plot the SAV results and error compared to SV if true
shouldplotFFT = true ; % Plot the FFT if true
shouldplotspectro = true; % Plot the spectrogram if true
shouldanimate = false ; % Make a gif of the plate if true
 
%% Declared parameters

Fs      = 44100 ;                     % Sampling rate

os      = 2  ;                         % Oversampling factor
T       =50;                          % Total time

%% Derived variable

D       = E * Lz^3 / 12 / (1-nu^2) ;
k       = (1/Fs)/os ;   
% Timestep
Ts      = floor(T/k) ;              % Number of time grid points
Tns     = floor(T*Fs);              % Number of desampled grid
t       =linspace(0,T,Ts);          % Time vector
tns     =linspace(0,T,Tns); 
x       =linspace(0,Lx,Nx+1);       % x space vector
y       =linspace(0,Ly,Ny+1);       % y space vector


%% Defining excitiation force

l0=1e8;

a0=zeros(Nmodes,1); 

a0(1)=1e-9;
multprop=1;
A=0.4 ; % Amplitude of forcing, units tba
modamp=1;

f0=Om(1)/(2*pi);
%shft=["-1","-2","-3","-4","-5","-6","-7","-8","-9","-10",...
%    "-11","-12","-13","-14","-15","-16","-17","-18","-19","-20"];
%shft=["+1","+2","+3","+4","+5","+6","+7","+8","+9","+10",...
%    "+11","+12","+13","+14","+15","+16","+17","+18","+19","+20"];
%shft=[""];
shft=["+20"];

sft1=string(linspace(-10,-1,10));
sft2=string(["+"+linspace(1,60,60)]);

%shft=[sft1,"",sft2];
%shft=+15;
%shft=string(["+"+linspace(41,60,60-41+1)]);

% fvec=[f0-1,f0-2,f0-3,f0-4,f0-5,f0-6,f0-7,f0-8,f0-9,f0-10,...
%     f0-11,f0-12,f0-13,f0-14,f0-15,f0-16,f0-17,f0-18,f0-19,f0-20];

fvec=[f0+15];
%fvec=f0+linspace(-20,20,41);

%fvec=f0+linspace(-10,60,60+10+1);
%fvec=f0+linspace(-30,60,10)%f0+15;

% fvec=[f0+1,f0+2,f0+3,f0+4,f0+5,f0+6,f0+7,f0+8,f0+9,f0+10,...
%     f0+11,f0+12,f0+13,f0+14,f0+15,f0+16,f0+17,f0+18,f0+19,f0+20];

%fvec=[f0+21,f0+22,f0+23,f0+24,f0+25];

ampex=["ampstep"];%,"ampreverse" ];
rev=[""];%,"reverse" ];
for igloo=1:1
for iloo=1:length(fvec)
ftic=fvec(iloo)
[pext,mdShapes] = Fapplied(A,t,Ts,Nx,Ny,Phi,D,rho,Lz,Om,k,h,Nmodes,"distributed",ampex(igloo),ftic); %calls the excitation function
 
pext=pext';
figure
plot(pext(1,1:3:floor(end)))

%% Excitation coupling data
% coup=mean(abs(pext(:,:)'));
% coup=coup/max(coup);
% figure
% hBar=bar(coup,'FaceColor','flat');
% set(gca,'YScale','log','FontSize',26)
% hBar.CData(1,:) = [.9 0.1 0.1];
% hBar.CData(6,:) = [.9 0.1 0.1];
% hBar.CData(11,:) = [.9 0.1 0.1];
% hBar.CData(17,:) = [.9 0.1 0.1];
% hBar.CData(22,:) = [.9 0.1 0.1];


%% Variable declaration

Sw=1;

Sf=1;


Id=speye(Nmodes);                               % Identity matrix

Dw1=diag((Om(1:Nmodes)));                       % Diagonal matrix of Omega

Dw2=diag((Om(1:Nmodes)).^2);                    % Diagonal matrix of Omega^2

Dw=diag((cos(k*Om(1:Nmodes))));                 % Diagonal for the exact lossless integrator

DV0=2*k^(-2)*(Id-diag((cos(k*Om(1:Nmodes)))));  % 

Ddiag=2*sparse(Dw);                             % 2*Sparse of Dw

D0sv=2*Id-(k^2)*Dw2;                            % 


qm=zeros(Nmodes,1);                             % Modal displacement vector at n-1

q0=zeros(Nmodes,1);                             % Modal displacement vector at n

                          % Modal deformation vector at n

qmsv=zeros(Nmodes,1);                           % Modal displacement vector at n-1 Stormer Verlet

q0sv=zeros(Nmodes,1);                           % Modal displacement vector at n Stormer Verlet

qssv=zeros(Nmodes,1);                           % Modal displacement vector at n+1 Stormer Verlet

nlsv=zeros(Nmodes,1);                           % Nonlinear term of Stormer Verlet

dUdq=zeros(Nmodes,1);                           % Derivative of the energy on q

g=zeros(Nmodes,1);                              % SAV nonlinear vector

En=zeros(1,Ts);                                 % Kinetic Energy

V0=zeros(1,Ts);                                 % Linear Potential

PSI0=zeros(1,Ts);                               % Psi time vector

dr=zeros(1,Ts);                                 % Drift of Psi over time

dr2=zeros(1,Ts);                                 % normalized drift

Q=zeros(Tns,Nmodes);                             % q time vector

Qsv=zeros(Tns,Nmodes);                           % q time vector Stormer-Verlet
Qssv=zeros(Tns,Nmodes);
Qasv=zeros(Tns,Nmodes);

ETA=zeros(Ts,Npsi);                           % eta time vector

eta=zeros(Npsi,1);                            % Modal stress vector at n

etam=zeros(Npsi,1);                           % Modal stress vector at n-1

c0=0.08;                                            %Frequency independant damping term

c1=0.04;                                              % Frequency dependant damping term

xi=Id;                                     % Modal damping matrix

xi=(c1*Om.^(0.75)+c0).*Id ;

%xi(1,1)=5e-4;  

%xi(:,:)=0;

xiv = diag(xi);


%l0=1e3;                                        % Drift control term

Omt2=(4/k^2)*(1 - 2*exp(-xiv*k).*cos(k*sqrt(Om.^2-xiv.^2)) +exp(-2*xiv*k)) ...
            ./(1 + 2*exp(-xiv*k).*cos(k*sqrt(Om.^2-xiv.^2)) +exp(-2*xiv*k));   % Omega Tilde square

Omt2=diag(Omt2); % Diagonal matrix of the modified frequencies


xit=(2/k)*(1-exp(-2*xiv*k))...
         ./(1 + 2*exp(-xiv*k).*cos(k*sqrt(Om.^2-xiv.^2)) +exp(-2*xiv*k)); % xi tilde


xit=diag(xit); % Diagonal matrix of the modified damping

DSM=(0.5*k*xi*Id+Id)^-1;                       % Damping term in the scheme

Dqmsv=0.5*k*xi*Id-Id;                          % Damping term in the Stormer-Verlet scheme

Dqpsv=0.5*k*xi*Id+Id;

%correction ?
DqmsvL=k*xit-Id;

Dq0svL=2*Id-Dw2*k^2;

DqpsvL=Id+0.25*Omt2*k^2+k*xit;

DexpsvL=inv(DqpsvL);
%


Dq0L=(2*Id-0.5*(Omt2*k^2));


DSMloss= inv(0.25*(Omt2*k^2) + 0.5*k*xit*Id  + Id); %Lossy version of the diagonal matrix of sherman morrisson




%%


%% Initialisation

%qm=flipud(sort(1e-6*rand(Nmodes,1)));           %random excitation

%qm(1)=1e-1;                                     % Initialisation of the displacement at n-1

q0=qm;                                          % Initialisation of the displacement at n

qmsv=qm;                                        % Initialisation of the displacement at n-1 Stormer-Verlet

q0sv=qmsv;                                      % Initialisation of the displacement at n Stormer-Verlet

Q(1,:)=q0;

Qsv(1,:)=q0sv;

enerr=1/(rho*Lz);                               % Energy multiplicator (see paper)

for ki = 1:Nmodes
    for ji =1:Nmodes
        for ii =1:Nmodes
            eta(ki)=eta(ki)-((E*Lz)/(2*zetafourth(ki)))*Hv(ii,ji,ki)*(q0(ii)*q0(ji)+2*q0(ii)*a0(ji)); % Initialisation of eta
        end
    end
end


etasv=eta;

etasvm=eta;
etasvp=eta;

ETA(1,:)=eta;

ETASV(1,:)=etasv;

U=enerr*(1/(2*E*Lz))*zetafourth(1:Npsi)'*0.5*(eta.^2+eta.^2);   %to change with actual energy (meaning etan-1)

ep=1e-11;                                       % Potential shift

psim1=sqrt(2*U+ep);                             % Initialisation of psi at n-1/2

PSI0(1)=psim1;        

if shouldtestSAV
%% SAV loop
countsav=1;
nsav=1;
tic
for n = 2 : Ts

    En(n)=0.5*sum(((q0-qm)/k).^2);  %Kinetic energy at timestep n

    %V0(n)=0.5*sum(DV0*q0.*qm);      %Linear potential energy at timestep n, lossess case
    
    V0(n) = 0.5*sum(Omt2*(0.5*(q0+qm)).^2);    % New linear potential for lossy cases

    eta(:)=0;

    for li = 1:Npsi
        for mi =1:Nmodes
            for ni =1:Nmodes
                eta(li)=eta(li)-((E*Lz)/(2*zetafourth(li)))*Hv(li,ni,mi)*(q0(mi)*q0(ni)+2*q0(mi)*a0(ni));         %eta computation 

            end
        end
    end

    ETA(n,:)=eta;
 
    U=enerr*(1/(2*E*Lz))*zetafourth(1:Npsi)'*(eta.^2);        %Nonlinear potential energy computation

    dUdq(:)=0;
    for ji = 1:Nmodes
        for ki =1:Npsi
            for ii =1:Nmodes
                dUdq(ji)=dUdq(ji)-eta(ki)*((q0(ii)+2*a0(ii))*Hv(ki,ii,ji));    %dU/dq computation

            end
        end
    end
    %g=enerr*(1/sqrt(2*U+ep))*dUdq;  %g vector computation at each timestep
    
    dr(n)=psim1-sqrt(2*U+ep);
    
    vel =((q0-qm)/k)+ep; % velocity

    g=enerr*(1/sqrt(2*U+ep))*dUdq-l0*dr(n)*(sign(vel)./sign(vel)'*vel); %g with drift control

    G(n)=g(1);

    %Q(n,:)=q0;


    if countsav==os
        countsav=0;
         Q(nsav,:)=q0;
         nsav=nsav+1;
    end
    countsav=countsav+1;

    % Matrix definitions


    Dqnm2=0.25*(k^2)*g*g'+0.5*xi*Id*k-Id;
   
    Dexp2=DSM-(DSM*0.25*(k^2)*g*g'*DSM)/(1+0.25*k^2*g'*DSM*g);


    DqpL= 0.25*(Omt2*k^2) + 0.5*k*xit*Id + 0.25*(k^2)*g*g' + Id;%n+1 for the exact lossy 
    DqmL=-0.25*(Omt2*k^2) + 0.5*k*xit*Id + 0.25*(k^2)*g*g' - Id;%n-1 for the exact lossy 
    %DexpL=inv(DqpL); 
    DexpL = DSMloss - (DSMloss*0.25*(k^2)*g*g'*DSMloss)/(1+g'*DSMloss*0.25*(k^2)*g);

    
    % Timestepping scheme LES 

    %qs=Dexp2*(D0sv*q0+Dqnm2*qm-g*(k^2)*psim1+k^2*pext(:,n));% +k^2*pext(:,n)); %SAV lossless
    %qs=Dexp2*(Ddiag*q0+Dqnm2*qm-g*(k^2)*psim1);% +k^2*pext(:,n)); %SAV lossless working
    

    qs=DexpL*(Dq0L*q0+DqmL*qm-g*(k^2)*psim1+k^2*pext(:,n)); % SAV exact lossy 
    
    psi0=psim1+0.5*g'*(qs-qm); % Psi time stepping
    %psi0=psim1+0.5*g'*(qs-qm)-k*l0*dr(n-1); % Psi control drift (probably
    %wrong, taken into account in g already


    %dr(n)=psi0-sqrt(2*U+ep);
    dr2(n)=(psi0-sqrt(2*U+ep))/sqrt(2*U+ep);


 

    % State swap

    PSI0(n)=psim1;
    qm=q0;
    q0=qs;
    psim1=psi0;

end
sav=toc
end
countsv=1;
nsv=1;

%% Stormer-Verlet loop
if shouldtestSV
tic
    %initialisation


    %eta computation

    t7 = Hv4*q0sv;
    t7 = reshape(t7,[Npsi,Nmodes]);
    Gc_1 = t7*q0sv;


    t8 = Hv4*a0;
    t8 = reshape(t8,[Npsi,Nmodes]);
    Gc_2 = t8*(qssv + q0sv);

    Gc = (Gc_1 + Gc_2);

    etasv = -etasvm - Gc;

for n = 2 : Ts

    if n == floor(Ts/10)
        disp('10% done')

    elseif n==floor(2*Ts/10)
        disp('20% done')

    elseif n==floor(3*Ts/10)
        disp('30% done')

    elseif n==floor(4*Ts/10)
        disp('40% done')

    elseif n==floor(5*Ts/10)
        disp('50% done')

    elseif n==floor(6*Ts/10)
        disp('60% done')

    elseif n==floor(7*Ts/10)
        disp('70% done')

    elseif n==floor(8*Ts/10)
        disp('80% done')

    elseif n==floor(9*Ts/10)
        disp('90% done')
    end

    %etasv(:)=0;

    %Left hand term
    t0=Hv2*(q0sv+a0);%half of the sum
    t0 = reshape(t0,[Npsi,Nmodes]);%reshape into a matrix
    G0 = (t0.'*t0);%Matrix of the left hand double sum


    mat_imp = Dqpsv + (E*k^2/rho)*G0; % implicit matrix


    %right hand term

    % (Hmn*Hks)/zeta^4 * qi(n-1)*aj*(qk(n-1)+ak) (static term)
    t1 = Hv2*q0sv;%half of the sum
    t1 = reshape(t1,[Npsi,Nmodes]);
    t4 = t1*a0;
    Ga = t0.'*t4; % Matrix

    % Hks * (qk(n-1)+ak) * (etal(n-2)-etal(n-1))/2 (dynamic term)
    eta_temp = (etasvm-etasv);
    t5 = Hv0*(q0sv + a0);
    t5 = reshape(t5,[Npsi,Nmodes]);
    Gb = (t5.'*eta_temp);

    Gtotal = Ga - Gb;

 


    % Timestepping scheme

    %qssv=DSM*(D0sv*q0sv+Dqmsv*qmsv+((k^2)/(rho*Lz))*nlsv+k^2*pext(:,n)); %Stormer Verlet
    qssv=mat_imp\(Dq0svL*q0sv + Dqmsv*qmsv - (k^2/(rho*Lz))*Gtotal+ k^2*pext(:,n));


       if countsv==os
        countsv=0;
        Qsv(nsv,:)=q0sv;
        Qssv(nsv,:)=(q0sv-qmsv)/k;
        Qasv(nsv,:)=(qssv-2*q0sv+qmsv)/k^2;
        nsv=nsv+1;
    end
    
    countsv=countsv+1;
   
    %eta computation

    % Hks/zeta^4 * qi(n)*qj(n-1)
    t7 = Hv4*qssv;
    t7 = reshape(t7,[Npsi,Nmodes]);
    Gc_1 = t7*q0sv;

    % Hks/zeta^4 * aj * (qi(n) + qi(n-1))
    t8 = Hv4*a0;
    t8 = reshape(t8,[Npsi,Nmodes]);
    Gc_2 = t8*(qssv + q0sv);

    Gc = (Gc_1 + Gc_2);

    etasvs = -etasv - (E*Lz)*Gc;

   
    % update
    qmsv=q0sv;
    q0sv=qssv;
    etasvm = etasv;
    etasv = etasvs;

%keyboard
end
SV=toc
end



if shouldplotSAV==true
   
%% Plotting the energy components
timecomp=3000;
figure
plot(t,En-En(timecomp),t,V0-V0(timecomp),t,((PSI0.^2)-(PSI0(timecomp)^2))/2)
title("Energy Components")
legend('Kinetic','Linear Potential','Nonlinear Potential')
%%
figure
EN=En+V0+(PSI0.^2)/2;
scatter(t,(EN-EN(timecomp))/EN(timecomp),'.','k')
xlim([0.01 0.1])
%title("Energy Balance")
xlabel("Time (s)")
ylabel("\Delta H")
set(gca,"FontSize",20)
%% Plotting Eta and Q

figure
plot(ETA(:,:),LineWidth=3)
title('\eta_k')
xlabel('Timestep')
ylabel('Amplitude')
set(gca,'FontSize',20)
figure
plot(Q(:,:),LineWidth=3)
title('w_k SAV')
xlabel('Timestep')
ylabel('Amplitude')
set(gca,'FontSize',20)
end
%%
if shouldtestSV
figure
plot(Qsv(:,:),LineWidth=3)
title('w_k Stormer-Verlet')
xlabel('Timestep')
ylabel('Amplitude')
set(gca,'FontSize',20)
end
%% Plotting the error
if shouldplotSAV==true
if shouldtestSV
figure
plot(tns,sum(abs(Q-Qsv)'),LineWidth=3)
title('w_k absolute error')
xlabel('Timestep')
ylabel('Amplitude')
set(gca,'FontSize',20)
xlim([0.01 0.1])
end

%% Plotting psi
figure
plot(t,PSI0,LineWidth=3)
title('Psi')
xlabel('Timestep')
ylabel('Amplitude')
set(gca,'FontSize',20)
xlim([0.01 T])
end
%% Plotting vibration point signal
wp=zeros(Tns,1);%displacement at a chosen point
ws=zeros(Tns,1);%velocity at a chosen point
wa=zeros(Tns,1);%acceleration at a chosen point
wpSAV=zeros(Tns,1);%displacement at a chosen point
for m = 1 : Nmodes
        wp=wp+Qsv(:,m)*mdShapes(floor(end/2),floor(end/2),m);
        ws=ws+Qssv(:,m)*mdShapes(floor(end/2),floor(end/2),m);
        wa=wa+Qasv(:,m)*mdShapes(floor(end/2),floor(end/2),m);
end
if shouldplotSAV
for m = 1 : Nmodes
        wpSAV=wpSAV+Q(:,m)*mdShapes(floor(end/2),floor(end/2),m);
end
end

figure
plot(tns,wp,LineWidth=3)
title('w at center')
xlabel('Time (s)')
ylabel('Amplitude')
set(gca,'FontSize',20)


%% FFT 
if shouldplotFFT ==true
[mod,phase,ft,faxis]=FFTAM(wp,tns,T);
if shouldplotSAV
[mod2,phase,ft,faxis]=FFTAM(wpSAV,tns,T);
end
figure
plot(faxis,mod,"LineWidth",3)
if shouldplotSAV
hold on
plot(faxis,mod2,"LineWidth",3)
end
xline(Om([1,end])/(2*pi))
if shouldplotSAV
legend('Stormer Verlet', 'SAV')
end
xlabel('Frequency (Hz)')
ylabel('Amplitude')

xlim([0 3000])
set(gca,'FontSize',20)
end
%% Spectrogram
if shouldplotspectro == true
    if shouldplotSAV
npwin=2^12;
nlap=npwin/2;
[s,fmat,tmat,ps] = spectrogram(wpSAV,hann(npwin),nlap,4*npwin,Fs,"ps");




figure
pcolor(tmat,fmat,log10(abs(s)))

shading interp
colorbar
%caxis([30 100])
%caxis([0.0 0.4])or
%caxis([-3 -1])
ylim([0 2000])
%clim([0,0.03])
set(gca,"FontSize",26)
ylabel("Frequency (Hz)")
xlabel("Time (s)")
%set (gca,'Xdir','reverse')
title ("Spectro SAV")
%colormap(flipud(bone))

clim([-14 -3])
[fun,ind]=max(abs(squeeze(s(:,:))));
ind2=linspace(ind(1),ind(end),length(ind));
fund=zeros(length(ind),1);
%fund(iter,:)=max(abs(squeeze(spec(iter,:,:))));
% 
% for itee=1:length(ind)
%         fund(itee)=abs(s(floor(ind2(itee)),itee));
% end
% figure
% plot(fund,"LineWidth",3)
% xlabel("Time")
% ylabel("Amplitude")
    end
if shouldtestSV == true
npwin=2^12;
nlap=npwin/2;
[s,fmat,tmat,ps] = spectrogram(wp,hann(npwin),nlap,4*npwin,Fs,"ps");




figure
pcolor(tmat,fmat,log10(abs(s)))

shading interp
colorbar
%caxis([30 100])
%caxis([0.0 0.4])or
%caxis([-3 -1])
ylim([0 5000])
%clim([0,0.03])
set(gca,"FontSize",26)
ylabel("Frequency (Hz)")
xlabel("Time (s)")
%set (gca,'Xdir','reverse')
title ("Spectro SV")
%colormap(flipud(bone))
clim([-9 -3])

[fun,ind]=max(abs(squeeze(s(:,:))));
ind2=linspace(ind(1),ind(end),length(ind));
fund=zeros(length(ind),1);
%fund(iter,:)=max(abs(squeeze(spec(iter,:,:))));
% 
% for itee=1:length(ind)
%         fund(itee)=abs(s(floor(ind2(itee)),itee));
% end
% figure
% plot(fund,"LineWidth",3)
% xlabel("Time")
% ylabel("Amplitude")
end
end
%% FFT over time
% npwin=2^14;
% nlap=npwin/2;
% [s,fmat,tmat,ps] = spectrogram(wp,hann(npwin),nlap,4*npwin,Fs,"ps");
% figure
% for itit=1:length(s(:,1))
% plot(fmat,log10(abs(s(:,itit))),"LineWidth",3)
% xlabel('Frequency (Hz)')
% ylabel('Amplitude')
% 
% xlim([0 5000])
% ylim([-9 -2])
% set(gca,'FontSize',20)
% pause(0.2)
% end
%% Plotting the plate

if shouldanimate
close all
limplt=max(max(max(abs(wp))));
t1=7.25;
t2=t1+0.2;



w0(:,:)=zeros(Ny+1,Nx+1);
w0(:,:)=0;
   for m = 1 : Nmodes
        w0=w0+a0(m)*mdShapes(:,:,m);
   end
%limplt=5e-4;
ds=4; % Desampling factor
w(:,:)=zeros(Ny+1,Nx+1);
time=floor(t1*length(t)/(10*ds));
 
figure('Position', [900 900 600 600],'Color','w')
gif('./img/VKplatetransi2_50modes.gif');
% w(:,:)=0;
%     for m = 1 : Nmodes
%         w=w+Qsv(time,m)*mdShapes(:,:,m);
%     end
%     subplot(2,3,[1,2,3,4])
%     surf(X,Y,w+w0)
% 
%     xlim([0 max(x)])
%     ylim([0 max(y)])
%     zlim([-limplt limplt])
%     clim([-limplt/4 limplt/4])
%     format short
%     legend([ num2str(time/Fs,'%.4f') "s"])
% 
%     set(gca,'xtick',[])
% 
%     set(gca,'ytick',[])
%     colormap(colorMap)
%     shading interp
% 
% 
%     %light("Style","local","Position",[-1,0.4,0.02])
%     %material metal; lighting gouraud ;


   %limplt=1;
  
for time= floor(2*t1*length(t)/(10*ds)):ds:floor(2*t2*length(t)/(10*ds))
   
    
    for m = 1 : Nmodes
        w=w+Qsv(time,m)*mdShapes(:,:,m);
    end
    surf(X,Y,w+w0)
    xlim([0 max(x)])
    ylim([0 max(y)])
    zlim([-limplt limplt])
    clim([-limplt/4 limplt/4])
    format short
    legend([ num2str(time/Fs,'%.4f') "s"])
    colormap(colorMap)
    set(gca,'xtick',[])
  
    set(gca,'ytick',[])
    shading interp
    %light("Style","local","Position",[-10,-10,0])
    %material metal 
    %lighting gouraud
    gif
    
    pause(0.01)
    w(:,:)=zeros(Ny+1,Nx+1);
end
end
%% Time signal at the center
%     wmid=zeros(length(Qsv(:,1)),1);
% for time= 1:length(Qsv(:,1))
%     for m = 1 : Nmodes
%         wmid(time)=wmid(time)+Qsv(time,m)*mdShapes(50,50,m);
%     end
% end
% 
% 
% figure
% plot(wmid+w0(50,50))
% %%
%  soundsc(wmid,1/k)

%%
if shouldtestSAV
figure
semilogy(abs(dr2))
xlabel("Timestep")
ylabel("Drift")
title(["Psi_0 drift lambda=1e2"])
set(gca,"FontSize",26)
end

%% save data :
Qsv=zeros(1,1);%to avoid too big files
save(strcat("./w10step2dBT=1w0=1e-9f=f0"+shft(iloo)+rev(igloo)+".mat"),'rho','E','nu','Lz','Lx','Ly','Nmodes','Phi','Om','Psi','Om2','Nx','Ny','h','X','Y','zetafourth','BCsPhi','BCsPsi','Hv','Npsi','wp','Fs','T','t','s','fmat','tmat','faxis','mod','A','Qsv','ws','wa')



close all
end
end
% figure
% plot(ws)