clear all
close all
clc
%%
colorMap = load('Ha2ColorMap.mat').Ha2ColorMap;
%%
% This code is made to check the convergence rate of SAV against Stormer Verlet%
% The input file should include :
%
%   USEFUL FOR CONTROL
%       BCsPhi - Displacement boundary conditions   | 4 x 2 vector
%       BCsPsi - Stress boundary conditions         | 4 x 2 vector
%       Om2 - Angular frequency of the Psi modes    | Nmodes x 1 vector
%       Lx - x length of the plate                  | float
%       Ly - y length of the plate                  | float
%       X - x space                                 | Ny+1 x Nx+1 matrix
%       Y - y space                                 | Ny+1 x Nx+1 matrix
%
%   USED FOR COMPUTATION
%       E - Young modulus                           | float
%       rho - Density                               | float
%       nu - Poisson's ratio                        | float
%       h - Space step                              | float
%       Lz - Thickness of the plate                 | float
%       Nmodes  - Number of modes                   | float
%       Hv - Coupling coeficients                   | Nmodes x Nmodes x Nmodes matrix
%       Nx - Number of points in the x direction    | float
%       Ny - Number of points in the y direction    | float
%       Om - Angular frequency of the Phi modes     | Nmodes x 1 vector
%       Phi - Eigenvectors of displacement          | (Nx+1*Ny+1) x Nmodes matrix
%       Psi - Eigenvectors of stress                | (Nx+1*Ny+1) x Nmodes matrix
%       zetafourth - Eigenvalues of the stress      | Nmodes x 1 vector
%
% The raw output is the Q matrix, that can be transformed by to physical
% displacement (w) by projecting it on the Phi vector.


%% Loading parameter file

load("./param/Test1mode.mat"); %Parameter file is generated by main


%% Switch cases
shouldtestSV = true ; % Make the comparison with Stormer Verlet if true
shouldplotSAV = true ; % Plot the SAV results and error compared to SV if true
shouldplotFFT = false ; % Plot the FFT if true
shouldplotspectro = false; % Plot the spectrogram if true
shouldanimate = false ; % Make a gif of the plate if true

%% Declared parameters
nos=10; %number of oversampling iterations
osmin=1;
osmax=2;
OS=floor(logspace(osmin,osmax,nos)) ;
for itera=1:nos
Fs      = 44100 ;% Sampling rate
os      = OS(itera)  ;                         % Oversampling factor
T       =0.1;                          % Total time

%% Derived variable

D       = E * Lz^3 / 12 / (1-nu^2) ;
k       = (1/Fs)/os ;               % Timestep
Ts      = floor(T/k) ;              % Number of time grid points
t       =linspace(0,T,Ts);          % Time vector
x       =linspace(0,Lx,Nx+1);       % x space vector
y       =linspace(0,Ly,Ny+1);       % y space vector


%% Defining excitiation force

A=0; % Amplitude of forcing, units tba

[pext,mdShapes] = Fapplied(A,t,Ts,Nx,Ny,Phi,D,rho,Lz,Om,k,h,Nmodes,"point","impact"); %calls the excitation function

pext=pext';

%% Variable declaration

Id=speye(Nmodes);                               % Identity matrix



Dw1=diag((Om(1:Nmodes)));                       % Diagonal matrix of Omega

Dw2=diag((Om(1:Nmodes)).^2);                    % Diagonal matrix of Omega^2

Dw=diag((cos(k*Om(1:Nmodes))));                 % Diagonal for the exact lossless integrator

DV0=2*k^(-2)*(Id-diag((cos(k*Om(1:Nmodes)))));  % 

Ddiag=2*sparse(Dw);                             % 2*Sparse of Dw

D0sv=2*Id-(k^2)*Dw2;                            % 


qm=zeros(Nmodes,1);                             % Modal displacement vector at n-1

q0=zeros(Nmodes,1);                             % Modal displacement vector at n

qmsv=zeros(Nmodes,1);                           % Modal displacement vector at n-1 Stormer Verlet

q0sv=zeros(Nmodes,1);                           % Modal displacement vector at n Stormer Verlet

qssv=zeros(Nmodes,1);                           % Modal displacement vector at n+1 Stormer Verlet

nlsv=zeros(Nmodes,1);                           % Nonlinear term of Stormer Verlet

dUdq=zeros(Nmodes,1);                           % Derivative of the energy on q

g=zeros(Nmodes,1);                              % SAV nonlinear vector

En=zeros(1,Ts);                                 % Kinetic Energy

V0=zeros(1,Ts);                                 % Linear Potential

PSI0=zeros(1,Ts);                               % Psi time vector

Q=zeros(Ts,Nmodes);                             % q time vector

Qsv=zeros(Ts,Nmodes);                           % q time vector Stormer-Verlet

ETA=zeros(Ts,Nmodes);                           % eta time vector

eta=zeros(Nmodes,1);                            % Modal stress vector at n

etam=zeros(Nmodes,1);                           % Modal stress vector at n-1

xi=0e-1*Id;                                      % Modal damping matrix

%xi(1,1)=0e-1;  

Omt2=(4/k^2)*(1 - 2*exp(-xi*k)*cos(k*sqrt(Om.^2-xi.^2)) +exp(-2*xi*k)) ...
            /(1 + 2*exp(-xi*k)*cos(k*sqrt(Om.^2-xi.^2)) +exp(-2*xi*k));   % Omega Tilde square
%Omt2=Om.^2;


xit=(2/k)*(1-exp(-2*xi*k))...
         /(1 + 2*exp(-xi*k)*cos(k*sqrt(Om.^2-xi.^2)) +exp(-2*xi*k)); % xi tilde

%DqpLsv=(1/k^2+Omt2/4+xit/k);

%Dq0Lsv=(2/k^2-Omt2/2);

%DqmLsv=(1/k^2+Omt2/4-xit/k);


Dq0L=(2-0.5*(Omt2*k^2));
Dq0Lne=(2-Dw2*k^2);



%DexpL= inv(Dqpl);

DSM=(0.5*k*xi*Dw1+Id)^-1;                       % Damping term in the scheme

Dqmsv=0.5*k*xi*Dw1-Id;                          % Damping term in the Stormer-Verlet scheme


%% Initialisation

%qm=flipud(sort(1e-6*rand(Nmodes,1)));           %random excitation

qm(1)=1e-5;                                     % Initialisation of the displacement at n-1

q0=qm;                                          % Initialisation of the displacement at n

qmsv=qm;                                        % Initialisation of the displacement at n-1 Stormer-Verlet

q0sv=qmsv;                                      % Initialisation of the displacement at n Stormer-Verlet

Q(1,:)=q0;

Qsv(1,:)=q0sv;

enerr=1/(rho*Lz);                               % Energy multiplicator (see paper)

for ki = 1:Nmodes
    for ji =1:Nmodes
        for ii =1:Nmodes
            eta(ki)=eta(ki)-((E*Lz)/(2*zetafourth(ki)))*Hv(ii,ji,ki)*q0(ii)*q0(ji); % Initialisation of eta
        end
    end
end

etasv=eta;

ETA(1,:)=eta;

ETASV(1,:)=etasv;

U=enerr*(1/(2*E*Lz))*zetafourth(1:Nmodes)'*0.5*(eta.^2+eta.^2);   %to change with actual energy (meaning etan-1)

ep=1e-14;                                       % Potential shift

psim1=sqrt(2*U+ep);                             % Initialisation of psi at n-1/2
PSI0(1)=psim1;
%% SAV loop

tic
for n = 2 : Ts

    En(n)=0.5*sum(((q0-qm)/k).^2);  %Kinetic energy at timestep n

    V0(n)=0.5*sum(DV0*q0.*qm);      %Linear potential energy at timestep n

    eta(:)=0;

    for li = 1:Nmodes
        for mi =1:Nmodes
            for ni =1:Nmodes
                eta(li)=eta(li)-((E*Lz)/(2*zetafourth(li)))*Hv(mi,ni,li)*q0(mi)*q0(ni);         %eta computation 

            end
        end
    end

    ETA(n,:)=eta;
 
    U=enerr*(1/(2*E*Lz))*zetafourth(1:Nmodes)'*(eta.^2);        %Nonlinear potential energy computation

    dUdq(:)=0;
    for ji = 1:Nmodes
        for ki =1:Nmodes
            for ii =1:Nmodes
                dUdq(ji)=dUdq(ji)-eta(ki)*(q0(ii)*Hv(ii,ji,ki));    %dU/dq computation

            end
        end
    end
    g=enerr*(1/sqrt(2*U+ep))*dUdq;  %g vector computation at each timestep

    G(n)=g(1);

    Q(n,:)=q0;

    % Matrix definitions


    Dqnm2=0.25*(k^2)*g*g'+0.5*xi*Dw1*k-Id;%n-1 for the lossy 
    
    Dexp2=DSM-(DSM*0.25*(k^2)*g*g'*DSM)/(1+0.25*k^2*g'*DSM*g);% Shermann Morisson of the lossy case

    Dqnp=0.25*(k^2)*g*g'+Id;%n+1 for the exact lossless
    Dqnm=0.25*(k^2)*g*g'-Id;%n-1 for the exact lossless
    Dexp=inv(Dqnp);         %explicit inverse of the n+1 term
    

    DqpL= 0.25*(Omt2*k^2) + 0.5*k*xit*Dw1 + 0.25*(k^2)*g*g' + Id;%n+1 for the exact lossy 
    DqmL=-0.25*(Omt2*k^2) + 0.5*k*xit*Dw1 + 0.25*(k^2)*g*g' - Id;%n-1 for the exact lossy 
    DexpL=inv(DqpL);                                             %explicit inverse of the n+1 term



    DqpLne=(0.25*(k^2)*g*g' + 0.5*k*xi*Dw1 + Id); %n+1 for the non-exact lossy 
    DqmLne=(0.25*(k^2)*g*g' + 0.5*k*xi*Dw1 - Id); %n-1 for the non-exact lossy 
    DexpLne=inv(DqpLne);                          %explicit inverse of the n+1 term


    
    %DqmL-Dqnm
    %Dexp2-Dexp
    %D0sv-Ddiag
    
    % Timestepping scheme

    %qs=Dexp2*(Ddiag*q0+Dqnm2*qm-g*(k^2)*psim1+k^2*pext(:,n)); %SAV lossless + losses (math wrong result good)

    %qs=Dexp*((2-Om^2*k^2)*q0+Dqnm*qm-g*(k^2)*psim1); %SAV lossless stupid version

    %qs=DexpLne*(Dq0Lne*q0+DqmLne*qm-g*(k^2)*psim1+k^2*pext(:,n)); %SAV lossy non exact 

    %qs=DexpL*(Dq0L*q0+DqmL*qm-g*(k^2)*psim1); %SAV exactlossy (not working yet)

    qs=Dexp*(Ddiag*q0+Dqnm*qm-g*(k^2)*psim1); % SAV exactlossless
    
    psi0=psim1+0.5*g'*(qs-qm); % Psi time stepping




 

    % State swap

    PSI0(n)=psim1;
    qm=q0;
    q0=qs;
    psim1=psi0;

end
sav=toc

%% Stormer-Verlet loop
if shouldtestSV
tic
for n = 2 : Ts

    etasv(:)=0;
    for li = 1:Nmodes
        for mi =1:Nmodes
            for ni =1:Nmodes
              
                etasv(li)=etasv(li)-((E*Lz)/(2*zetafourth(li)))*Hv(mi,ni,li)*q0sv(mi)*q0sv(ni); %eta computation for Stormer Verlet

            end
        end
    end

  

    nlsv(:)=0;
    for ki = 1:Nmodes
        for ji =1:Nmodes
            for ii =1:Nmodes
                nlsv(ki)=nlsv(ki)+Hv(ki,ji,ii)*q0sv(ii)*etasv(ji);      %Stormer Verlet nonlinear term computation
            end
        end
    end
 

    Qsv(n,:)=q0sv;

    % Timestepping scheme

    qssv=DSM*(D0sv*q0sv+Dqmsv*qmsv+((k^2)/(rho*Lz))*nlsv+k^2*pext(:,n)); %Stormer Verlet

    % State swap

    qmsv=q0sv;
    q0sv=qssv;


end
SV=toc
itera
end

%%
err=abs(Qsv(end)-Q(end))/abs(Qsv(end));
ERR(itera)=err;

end
%% Error plot
OS2=logspace(osmin,osmax,nos);
rate1=ERR(1)*logspace(0,-(osmax-osmin),nos);
rate2=ERR(1)*logspace(0,-2*(osmax-osmin),nos);
figure
loglog(OS,ERR,"LineWidth",6)
hold on
loglog(OS2,rate2,"LineStyle","--","LineWidth",4)
set(gca,'FontSize',25)
title("Convergenge rate of SAV against SV, initial excitation 1e-3")
xlabel("Oversampling")
ylabel("Relative error")
legend("Error", "Slope 2")
%%

if shouldplotSAV==true
%% Plotting the energy components
timecomp=3000;
figure
plot(t,En-En(timecomp),t,V0-V0(timecomp),t,((PSI0.^2)-(PSI0(timecomp)^2))/2)
title("Energy Components")
legend("Kinetic","Linear Potential","Psi")
figure
EN=En+V0+(PSI0.^2)/2;
scatter(t,(EN-EN(timecomp))/EN(timecomp),'.')
xlim([0.001 T])
title("Energy Balance exact")
set(gca,'FontSize',20)
%% Plotting Eta and Q
% figure
% plot(ETA(:,:),LineWidth=3)
% title('\eta_k')
% xlabel('Timestep')
% ylabel('Amplitude')
% set(gca,'FontSize',20)
figure
plot(Q(:,:),LineWidth=3)
title('w_k SAV')
xlabel('Timestep')
ylabel('Amplitude')
set(gca,'FontSize',20)
end
%%
 if shouldtestSV
figure
plot(Qsv(:,:),LineWidth=3)
title('w_k Stormer-Verlet')
xlabel('Timestep')
ylabel('Amplitude')
set(gca,'FontSize',20)
end
%% Plotting the error
if shouldplotSAV==true
if shouldtestSV
% 


end

%% Plotting psi
% figure
% plot(PSI0,LineWidth=3)
% title('Psi')
% xlabel('Timestep')
% ylabel('Amplitude')
% set(gca,'FontSize',20)

end
%% Plotting vibration point signal
% wp=zeros(n,1);%displacement at a chosen point
% for m = 1 : Nmodes
%         wp=wp+Qsv(:,m)*mdShapes(floor(end/2),floor(end/2),m);
% end
% 
% for m = 1 : Nmodes
%         wpSAV=wp+Qsv(:,m)*mdShapes(floor(end/2),floor(end/2),m);
% end
% 
% 
% figure
% plot(t,wp,LineWidth=3)
% title('w at center')
% xlabel('Time (s)')
% ylabel('Amplitude')
% set(gca,'FontSize',20)


%% FFT 
if shouldplotFFT ==true
[mod,phase,ft,faxis]=FFTAM(wp,t,T);
[mod2,phase,ft,faxis]=FFTAM(wpSAV,t,T);

figure
plot(faxis,mod,faxis,mod2,"LineWidth",3)
legend('Stormer Verlet', 'SAV')
xlabel('Frequency (Hz)')
ylabel('Amplitude')
%xlim([0 600])
set(gca,'FontSize',20)
end
%% Spectrogram
if shouldplotspectro == true
npwin=2^16;
nlap=npwin/2;
[s,fmat,tmat,ps] = spectrogram(wp,hann(npwin),nlap,4*npwin,Fs*os,"ps");




figure
pcolor(tmat,fmat,log10(abs(s)))

shading interp
colorbar
%caxis([30 100])
%caxis([0.0 0.4])or
caxis([-3 -1])
ylim([0 2000])
set(gca,"FontSize",26)
ylabel("Frequency (Hz)")
xlabel("Time (s)")
%set (gca,'Xdir','reverse')
title ("Sweep from 100 to 700 Hz micin multimembrane")
colormap(flipud(bone))
end

%% Plotting the plate

if shouldanimate
close all
limplt=max(max(max(abs(Q*75))));
ds=4; % Desampling factor
w(:,:)=zeros(Ny+1,Nx+1);
time=1;
figure('Position', [900 900 600 600],'Color','w')
w(:,:)=0;
    for m = 1 : Nmodes
        w=w+Qsv(time,m)*mdShapes(:,:,m);
    end
    subplot(2,3,[1,2,3,4])
    surf(X,Y,w)
    
    xlim([0 max(x)])
    ylim([0 max(y)])
    zlim([-limplt limplt])
    %colormap(colorMap)
    shading interp
    

    %light("Style","local","Position",[-1,0.4,0.02])
    %material metal; lighting gouraud ;
%gif('./img/VKplateExamplemembrane.gif');

for time= ds+1:ds:floor(length(t)/50)
   w(:,:)=0;
    for m = 1 : Nmodes
        w=w+Qsv(time,m)*mdShapes(:,:,m);
    end
    surf(X,Y,w)
    xlim([0 max(x)])
    ylim([0 max(y)])
    zlim([-limplt limplt])
    clim([-limplt/2 limplt/2])
    format short
    legend([ num2str(time/Fs,'%.4f') "s"])
    colormap(colorMap)
    set(gca,'xtick',[])
  
    set(gca,'ytick',[])
    shading interp
    %light("Style","local","Position",[-10,-10,0])
    %material metal 
    %lighting gouraud
    %gif
    
    pause(0.01)    
end
end
% %% Time signal at the center
%     wmid=zeros(T/k,1);
% 
%     for m = 1 : Nmodes
%         wmid=wmid+Qsv(:,m)*mdShapes(floor(Nx/2),floor(Ny/2),m);
%     end
% 
% 
% figure
% plot(wmid)
% %%
%  soundsc(wmid,1/k)